<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('Task1')->setSeparator(' - ')->setAutoEscape(false) ?>
		
		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico')); ?>
	</head>
	<body>
		<div class="container">
			<a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
		</div>
		<div class="container">
			<?php echo $this->content; ?>
		</div>
		<?php echo $this->inlineScript() ?>
	</body>
</html>
