<?php
// module/Task1/view/task1/task/index.phtml:

$this->headTitle('Task for Veeam');
?>
<h1><?php echo $this->escapeHtml($this->translate('Vacancies')); ?></h1>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<table>
	<tr>
		<td><?php echo $this->formRow($form->get('lang')) ?></td>
		<td><?php echo $this->formRow($form->get('department')) ?></td>
	</tr>
	<tr>
		<td><?php echo $this->formSubmit($form->get('submit')) ?></td>
		<td>&nbsp;</td>
	</tr>
</table>
<?php echo $this->form()->closeTag() ?>

<table border="1">
<tr>
    <th><?php echo $this->translate('Department') ?></th>
    <th><?php echo $this->translate('Name') ?></th>
    <th><?php echo $this->translate('Description') ?></th>
</tr>
<?php foreach ($vacancies as $vacancy) :
	$translateVacancy = $vacancy->getTranslateByLang($lang);
?>
<tr>
    <td><?php echo $this->escapeHtml($vacancy->getDepartment()->getName());?></td>
    <td><?php echo $this->escapeHtml($translateVacancy->getName());?></td>
    <td><?php echo $this->escapeHtml($translateVacancy->getDesc());?></td>
</tr>
<?php endforeach; ?>
</table>